### PR TITLE
Update Deps to align with Con_Cache and Elixir 1.6

### PR DESCRIPTION
**Pull request by pedromvieira**
Updated Deps to align with Con_Cache and Elixir 1.6
Updated Supervisor Start Link.
Tested with Erlang 21.0 and Elixir 1.6.6

### CODE REVIEW

**Review by fcevado — APPROVED** [review]

**Comment by fcevado** [comment]
thanks for the update. I'll try to push the new version to hex asap.

**Comment by denispeplin** [comment]
@fcevado , the latest release on hex is already from 2017.

**Comment by fcevado** [comment]
@denispeplin published. thanks for remembering me. sorry for the delay

**Comment by denispeplin** [comment]
Thanks for publishing!

**Pull request merged**
